#!/usr/bin/env php
<?php

use PHPStan\DependencyInjection\ContainerFactory;
use PHPStan\PhpDoc\TypeNodeResolver;
use PHPStan\PhpDoc\TypeStringResolver;
use PHPStan\PhpDocParser\Lexer\Lexer;
use PHPStan\PhpDocParser\Parser\TypeParser;
use PHPStan\Type\VerbosityLevel;

require_once __DIR__ . '/../vendor/autoload.php';

$input = fgets(STDIN);
$container = (new ContainerFactory(__DIR__))->create(sys_get_temp_dir(), [], []);
$resolver = new TypeStringResolver(
    new Lexer(),
    new TypeParser(),
    $container->getByType(TypeNodeResolver::class),
);
$type = $resolver->resolve($input);
echo $type->describe(VerbosityLevel::precise());
