#!/usr/bin/env php
<?php

use PHPStan\DependencyInjection\ContainerFactory;
use PHPStan\PhpDoc\TypeNodeResolver;
use PHPStan\PhpDoc\TypeStringResolver;
use PHPStan\PhpDocParser\Lexer\Lexer;
use PHPStan\PhpDocParser\Parser\TypeParser;
use PHPStan\Type\VerbosityLevel;

require_once __DIR__ . '/../vendor/autoload.php';

$container = (new ContainerFactory(__DIR__))->create(sys_get_temp_dir(), [], []);
$resolver = new TypeStringResolver(
    new Lexer(),
    new TypeParser(),
    $container->getByType(TypeNodeResolver::class),
);

$mode = readLine();

switch ($mode) {
    case 'canonicalize':
        $input = readLine();
        echo $resolver->resolve($input)->describe(VerbosityLevel::precise());
        break;
    case 'compatibility':
        $super = $resolver->resolve(readLine());
        $sub = $resolver->resolve(readLine());
        echo $super->accepts($sub, true)->yes() ? 'true' : 'false';
        break;
    default:
        echo \Safe\sprintf('Unknown mode "%s"', $mode);
        exit(1);
}
